# Generated by Django 4.1.8 on 2023-05-21 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_feedback_email_feedback_name_feedback_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='subject',
        ),
    ]
