# Generated by Django 4.1.8 on 2023-05-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_feedback_email_remove_feedback_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('manager', 'manager'), ('owner', 'owner'), ('admin', 'admin')], default='customer', max_length=255),
        ),
    ]
